name: Check Tesla Order Status
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora automáticamente
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Bypass Login (Create cache.json)
        run: |
          echo '{"refresh_token": "${{ secrets.TESLA_REFRESH_TOKEN }}", "access_token": "init"}' > cache.json
        # Esto crea el archivo que el script busca para saltarse el navegador

      - name: Run script
        run: |
          # Usamos 'echo' para responder automáticamente a cualquier pregunta del script
          echo "n" | python tesla_order_status.py
        env:
          TESLA_USER: ${{ secrets.TESLA_USER }}
